-- =============================================================================
-- PathFinder Database Schema
-- =============================================================================
--
-- This file defines the complete relational schema for the PathFinder learning
-- path planner.  It is provided for reference and local development; in
-- production the schema is managed via Supabase migrations.
--
-- OVERVIEW
-- --------
-- The schema has two clusters of tables:
--
--   User identity
--     users            → Authenticated accounts (email + password hash)
--     user_profiles    → Optional background data used for AI personalisation
--
--   Learning content (all cascade from plans downward)
--     plans            → A named learning goal with progress counters
--     nodes            → Knowledge-graph nodes belonging to a plan
--     edges            → Directed prerequisite relationships between nodes
--     learning_sessions → Append-only activity log (node status changes)
--     notes            → Free-text annotations attached to individual nodes
--
-- CASCADE DELETES
-- ---------------
-- Deleting a user removes:   user_profiles, learning_sessions, notes
-- Deleting a plan removes:   nodes, edges, notes, learning_sessions
-- Deleting a node removes:   edges (both sides), notes, learning_sessions
--
-- PERFORMANCE INDEXES
-- -------------------
-- Five composite indexes cover the most frequent query patterns:
--   idx_plans_user_status_access      → Plan list page (filter by user + status,
--                                       order by recent access)
--   idx_nodes_plan_status             → Progress queries (count learned vs total)
--   idx_edges_plan                    → Graph load (fetch all edges for a plan)
--   idx_notes_user_plan_created       → Notes feed (user + plan, newest first)
--   idx_learning_sessions_user_created → Activity feed (user, newest first)
-- =============================================================================


-- -----------------------------------------------------------------------------
-- users
-- Stores one row per registered account.  The id column uses TEXT (typically
-- a UUID generated by the application) rather than a serial integer to make
-- IDs portable across environments without sequence conflicts.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            TEXT        PRIMARY KEY,
  email         TEXT        UNIQUE NOT NULL,          -- Login identifier; must be globally unique
  password_hash TEXT        NOT NULL,                 -- bcrypt or argon2 hash; never store plain text
  created_at    TIMESTAMPTZ DEFAULT now()
);


-- -----------------------------------------------------------------------------
-- user_profiles
-- Stores one optional profile per user, used by the AI to personalise the
-- knowledge graph (e.g. skipping nodes the user already knows, adjusting
-- difficulty).  One-to-one with users via the UNIQUE constraint on user_id.
-- Cascades deletes: removing a user also removes their profile.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_profiles (
  id                  TEXT        PRIMARY KEY,
  user_id             TEXT        UNIQUE NOT NULL,
  occupation          TEXT,                                       -- e.g. "Software Engineer"
  education           TEXT,                                       -- e.g. "Bachelor's in CS"
  programming_level   TEXT        DEFAULT '入门',                  -- Beginner / Intermediate / Advanced
  math_level          TEXT        DEFAULT '入门',                  -- Beginner / Intermediate / Advanced
  abilities           JSONB       DEFAULT '[]'::jsonb,            -- Array of skill strings
  mastered_knowledge  JSONB       DEFAULT '[]'::jsonb,            -- Array of topic strings already learned
  updated_at          TIMESTAMPTZ DEFAULT now(),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- plans
-- A learning plan ties a user's goal to a versioned knowledge graph.
-- progress and total are denormalised counters maintained by the application
-- to avoid expensive COUNT queries on every plan-list request.
-- Status lifecycle: 'active' → 'completed' or 'archived'.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS plans (
  id              TEXT        PRIMARY KEY,
  user_id         TEXT        NOT NULL,
  title           TEXT        NOT NULL,                -- Human-readable goal name
  original_input  TEXT,                               -- Verbatim goal text the user typed
  target_node_id  TEXT,                               -- ID of the terminal "goal" node
  progress        INTEGER     DEFAULT 0,              -- Count of nodes with status = 'learned'
  total           INTEGER     DEFAULT 0,              -- Total node count (including skipped)
  status          TEXT        DEFAULT 'active',       -- 'active' | 'archived' | 'completed'
  last_access_at  TIMESTAMPTZ DEFAULT now(),          -- Updated whenever the plan is opened
  created_at      TIMESTAMPTZ DEFAULT now(),
  FOREIGN KEY (user_id) REFERENCES users(id)
);


-- -----------------------------------------------------------------------------
-- nodes
-- Each node represents one knowledge topic in a plan's directed graph.
-- Rich metadata (why, what, mastery, resources) is stored as JSONB so the
-- application can read it back without joins.
-- Cascades deletes from plan: removing a plan wipes all its nodes.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS nodes (
  id          TEXT              PRIMARY KEY,
  plan_id     TEXT              NOT NULL,
  name        TEXT              NOT NULL,                      -- Topic label, e.g. "Gradient Descent"
  status      TEXT              DEFAULT 'unlearned',           -- 'unlearned' | 'learned' | 'skipped'
  x           DOUBLE PRECISION  DEFAULT 0,                     -- Canvas X position (pixels)
  y           DOUBLE PRECISION  DEFAULT 0,                     -- Canvas Y position (pixels)
  why         TEXT,                                            -- Why this topic matters for the goal
  what        JSONB             DEFAULT '[]'::jsonb,           -- Array of concept strings
  mastery     JSONB             DEFAULT '[]'::jsonb,           -- Array of mastery-criterion strings
  prompt      TEXT,                                            -- AI-generated study question
  resources   JSONB             DEFAULT '[]'::jsonb,           -- Array of {name, url, reason} objects
  is_target   BOOLEAN           DEFAULT FALSE,                 -- TRUE for the single goal node
  domain      TEXT,                                            -- Broad domain label, e.g. "Mathematics"
  created_at  TIMESTAMPTZ       DEFAULT now(),
  FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- edges
-- Directed prerequisite edges: from_node_id must be learned before to_node_id.
-- The UNIQUE constraint prevents duplicate edges within the same plan.
-- All three cascade rules ensure edges are pruned when either endpoint or the
-- parent plan is deleted.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS edges (
  id           TEXT  PRIMARY KEY,
  plan_id      TEXT  NOT NULL,
  from_node_id TEXT  NOT NULL,   -- Prerequisite node (learn this first)
  to_node_id   TEXT  NOT NULL,   -- Dependent node
  FOREIGN KEY (plan_id)      REFERENCES plans(id) ON DELETE CASCADE,
  FOREIGN KEY (from_node_id) REFERENCES nodes(id) ON DELETE CASCADE,
  FOREIGN KEY (to_node_id)   REFERENCES nodes(id) ON DELETE CASCADE,
  UNIQUE(plan_id, from_node_id, to_node_id)           -- No duplicate edges per plan
);


-- -----------------------------------------------------------------------------
-- learning_sessions
-- Append-only audit log recording every node status change.
-- Used by the stats router to compute streaks, velocity, and activity history.
-- node_name is denormalised for display in activity feeds without joins.
-- Cascades deletes from both user and plan for easy data cleanup.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS learning_sessions (
  id         TEXT        PRIMARY KEY,
  user_id    TEXT        NOT NULL,
  plan_id    TEXT        NOT NULL,
  node_id    TEXT        NOT NULL,
  node_name  TEXT,                        -- Denormalised for activity-feed display
  action     TEXT        NOT NULL,        -- e.g. 'learned', 'skipped', 'reset'
  created_at TIMESTAMPTZ DEFAULT now(),
  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
  FOREIGN KEY (plan_id)  REFERENCES plans(id)  ON DELETE CASCADE,
  FOREIGN KEY (node_id)  REFERENCES nodes(id)  ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- notes
-- Free-text annotations written by a user for a specific node in a plan.
-- One user can have multiple notes per node (no UNIQUE constraint).
-- Cascades deletes from plan, node, and user.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notes (
  id         TEXT        PRIMARY KEY,
  plan_id    TEXT        NOT NULL,
  node_id    TEXT        NOT NULL,
  user_id    TEXT        NOT NULL,
  content    TEXT        NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  FOREIGN KEY (plan_id)  REFERENCES plans(id)  ON DELETE CASCADE,
  FOREIGN KEY (node_id)  REFERENCES nodes(id)  ON DELETE CASCADE,
  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE
);


-- =============================================================================
-- Performance indexes
-- =============================================================================

-- Plan list page: filter active plans for a user, ordered by most recently accessed.
CREATE INDEX IF NOT EXISTS idx_plans_user_status_access
  ON plans(user_id, status, last_access_at DESC);

-- Node status queries: fetch all nodes for a plan filtered by status
-- (used to compute progress and find the next unlearned node).
CREATE INDEX IF NOT EXISTS idx_nodes_plan_status
  ON nodes(plan_id, status);

-- Graph load: retrieve all edges belonging to a plan in a single scan.
CREATE INDEX IF NOT EXISTS idx_edges_plan
  ON edges(plan_id);

-- Notes feed: list notes for a user within a plan, newest first.
CREATE INDEX IF NOT EXISTS idx_notes_user_plan_created
  ON notes(user_id, plan_id, created_at DESC);

-- Activity feed: list all learning events for a user, newest first.
CREATE INDEX IF NOT EXISTS idx_learning_sessions_user_created
  ON learning_sessions(user_id, created_at DESC);
