import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "concept_tree_language";
const DEFAULT_LANGUAGE = "en";

const messages = {
  en: {
    "language.switch": "Switch language",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.close": "Close",
    "common.back": "Back",
    "common.continue": "Continue",
    "common.loading": "Loading...",
    "nav.myLearning": "My Learning",
    "nav.signIn": "Sign in / Create account",
    "nav.signOut": "Sign out",
    "nav.home": "Home",
    "nav.newMap": "New learning map",
    "nav.workspace": "Workspace navigation",
    "nav.recentPlans": "Recent plans",
    "nav.openMenu": "Open navigation",
    "nav.closeMenu": "Close navigation",
    "home.eyebrow": "Adaptive learning workspace",
    "home.title.before": "What would you like to ",
    "home.title.emphasis": "master",
    "home.title.after": " today?",
    "home.subtitle": "Turn a learning goal into a focused, personalized concept map.",
    "home.goal.placeholder": "Try: Help me understand how backpropagation trains a neural network. I know Python, but my math is basic...",
    "home.goal.analyzing": "Analyzing...",
    "home.goal.generate": "Create learning map",
    "home.suggestions.label": "Try an example",
    "home.suggestion.backprop": "Understand backpropagation",
    "home.suggestion.python": "Learn Python data analysis",
    "home.suggestion.transformer": "Explore Transformer architecture",
    "home.today": "Today",
    "home.plans": "Learning plans",
    "home.progress": "Progress",
    "home.lastStudied": "Last studied: {value}",
    "home.justNow": "Just now",
    "home.continue": "Continue learning",
    "home.goLearn": "Start this step",
    "home.currentProgress": "Current progress",
    "home.neverStarted": "You have not started this plan yet",
    "home.daysSince": "{count} days since your last session",
    "home.setDeadline": "Set deadline",
    "home.deadline": "Due {date}",
    "home.reminderOn": "Reminder on",
    "home.recommendation.ai": "AI-recommended next step",
    "home.recommendation.local": "Rule-based next step",
    "home.recommendation.heading": "Continue with the next key concept",
    "home.recommendation.fallback": "This is the most useful next step for your plan.",
    "home.recommendation.localHelp": "AI is unavailable, so this suggestion uses prerequisites and your deadline.",
    "home.recommendation.loading": "Preparing today’s recommendation...",
    "home.plan.rename": "Rename",
    "home.plan.pause": "Pause",
    "home.plan.resume": "Resume",
    "home.plan.archive": "Archive",
    "home.plan.today": "Today’s pick",
    "home.plan.next": "Next concept",
    "home.goal.confirmTitle": "Confirm learning goal",
    "home.goal.edit": "Edit input",
    "home.goal.confirm": "Create map",
    "home.goal.interpreted": "Interpreted goal",
    "home.goal.purpose": "Learning intent",
    "home.purpose.explore": "Explore the field",
    "home.purpose.exploreHelp": "A lighter map for building initial understanding",
    "home.purpose.apply": "Build something",
    "home.purpose.applyHelp": "Focus on practical concepts you can use quickly",
    "home.purpose.master": "Master the system",
    "home.purpose.masterHelp": "A more complete and rigorous learning path",
    "home.deadline.title": "Set deadline",
    "home.deadline.help": "Set a target date for “{name}”. Today’s priorities will adapt to it.",
    "home.deadline.clear": "Clear deadline",
    "home.deadline.save": "Save date",
    "home.rename.title": "Rename plan",
    "home.rename.placeholder": "Enter a new plan name",
    "status.active": "Active",
    "status.paused": "Paused",
    "status.completed": "Completed",
    "status.archived": "Archived",
    "frequency.daily": "Daily",
    "frequency.weekly": "Weekly review",
    "frequency.custom": "{count} days a week",
    "frequency.flexible": "Flexible",
    "reminder.overdue": "Needs attention",
    "reminder.due": "Study today",
    "reminder.deadline": "Deadline soon",
    "reminder.paused": "Reminders paused",
    "reminder.normal": "On track",
    "reminder.headline.paused": "“{name}” is paused",
    "reminder.headline.onTrack": "Keep moving forward with “{name}”",
    "reminder.headline.due": "Today is a good day to continue “{name}”",
    "reminder.headline.overdue": "“{name}” is {count} days behind",
    "reminder.headline.deadline": "{count} days left for “{name}”",
    "reminder.detail.paused": "Paused plans will not send study prompts. Resume whenever you are ready.",
    "reminder.detail.onTrack": "Your current rhythm suggests studying every {count} days.",
    "reminder.detail.due": "Based on your rhythm, today is the right time to continue this plan.",
    "reminder.detail.overdue": "Your last session was {count} days ago, beyond your current rhythm.",
    "reminder.detail.deadline": "Prioritize this plan over the next few days if you want to finish on time.",
    "reminder.detail.deadlinePast": "The target date has passed. Resume your rhythm or adjust the plan.",
    "toast.deadlineUpdated": "Deadline updated",
    "toast.deadlineCleared": "Deadline cleared",
    "toast.deadlineFailed": "Could not save the deadline. The previous setting was restored.",
    "toast.signInForAi": "Sign in to use AI generation.",
    "toast.sessionExpired": "Your session expired. Please sign in again.",
    "toast.parseFailed": "Could not analyze the goal. Please try again.",
    "toast.graphFailed": "Could not create the learning map. Please try again.",
    "auth.subtitle": "Your adaptive learning workspace",
    "auth.login": "Sign in",
    "auth.register": "Create account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Name",
    "auth.passwordHint": "At least 6 characters",
    "auth.loggingIn": "Signing in...",
    "auth.registering": "Creating account...",
    "auth.haveAccount": "Already have an account?",
    "auth.noAccount": "New to LearningMaster?",
    "auth.agreement": "By continuing, you agree to the Terms of Service and Privacy Policy.",
    "auth.error.required": "Enter your email and password.",
    "auth.error.password": "Password must be at least 6 characters.",
    "auth.error.email": "Enter a valid email address.",
    "auth.error.generic": "Something went wrong. Please try again.",
    "auth.error.network": "Could not reach the server. Check that the backend is running.",
    "deep.title": "Deep Learn",
    "deep.backToMap": "Back to learning map",
    "deep.concepts": "Concepts",
    "deep.workspace": "Learning workspace",
    "deep.preparing": "Preparing your learning workspace...",
    "deep.failed": "Could not prepare the learning workspace",
    "deep.resizeConcepts": "Resize concepts and learning workspace",
    "deep.resizeAssistant": "Resize learning workspace and side panel",
    "deep.resizeHint": "Drag to resize. Double-click to reset.",
    "deep.restart": "Restart",
    "deep.restartTitle": "Restart this session?",
    "deep.restartHelp": "Your current Deep Learn progress will be cleared and the explanation will restart from the first concept.",
    "deep.restartConfirm": "Restart session",
    "deep.note.generating": "Creating note...",
    "deep.note.complete": "Completion note ↗",
    "deep.note.untitled": "Untitled note",
    "deep.note.label": "Note",
    "deep.note.reader": "Note reader",
    "deep.note.edit": "Edit note",
    "deep.note.delete": "Delete note",
    "deep.note.deleteAction": "Delete",
    "deep.note.deleteNamed": "Delete note {name}",
    "deep.note.close": "Close note reader",
    "deep.initializing.title": "Preparing your first Deep Learn session",
    "deep.initializing.subtitle": "The session for {name} is initialized once, then your progress is restored automatically.",
    "deep.initializing.concepts": "Reading the concept list and learning goal",
    "deep.initializing.depth": "Calibrating the teaching depth",
    "deep.initializing.lesson": "Creating the first explanation and diagnostic question",
    "deep.currentConcept": "Current concept",
    "deep.sidebar": "Side workspace",
    "deep.conceptsArea": "Concept list area",
    "deep.sidebarContainer": "Side workspace container",
    "deep.progress": "Progress",
    "deep.weakPoints": "Weak points",
    "deep.answerPrompt": "Answer the following questions:",
    "deep.outline.open": "Open learning outline",
    "deep.outline.question": "Question {count}",
    "deep.outline.feedback": "Feedback {count}",
    "deep.outline.diagram": "Diagram {count}",
    "deep.outline.image": "Image {count}",
    "deep.aiReply": "AI response",
    "deep.input.thinking": "AI is thinking...",
    "deep.input.answer": "Type your answer...",
    "deep.input.choose": "Choose the next action...",
    "deep.send": "Send",
    "deep.pin": "Pin to concepts",
    "deep.diagram": "Diagram",
    "deep.command.continue": "Continue →",
    "deep.command.expand": "Go deeper",
    "deep.command.skip": "Skip",
    "deep.command.reteach": "Explain differently",
    "deep.command.confirm_test": "Start quiz",
    "deep.command.not_ready": "Review first",
    "deep.command.restart": "Restart",
    "deep.notes": "Notes",
    "deep.note.suggest": "Add to notes?",
    "deep.note.ignore": "Not now",
    "deep.note.add": "Add",
    "deep.note.count": "{count} notes for this concept",
    "deep.note.new": "New note",
    "deep.note.empty": "No notes for this concept yet.",
    "deep.note.editorHelp": "Edit on the left, preview on the right",
    "deep.note.saved": "Saved",
    "deep.note.placeholder": "Markdown supported...",
    "deep.note.preview": "Preview",
    "deep.image.generating": "Creating image...",
    "deep.image.failed": "Could not create image",
    "deep.image.unavailable": "Image unavailable",
    "deep.image.loadFailed": "Could not load image",
    "deep.image.pinned": "Pinned visuals",
    "deep.image.unpin": "Unpin visual",
    "deep.image.closePreview": "Close preview",
    "deep.image.fallbackTitle": "Architecture diagram",
    "deep.image.fallbackNote": "Reliable fallback",
    "deep.image.fallbackAria": "{name} architecture",
    "deep.image.fallbackTopic": "Learning concept",
    "deep.image.concept": "Concept",
    "deep.image.mechanism": "Mechanism",
    "deep.image.outcome": "Outcome",
    "deep.search.searching": "Searching reference material...",
    "deep.search.fallback": "No external sources were available. Continuing with the model response.",
    "deep.search.done": "References are ready.",
    "deep.sources": "Sources",
    "assistant.chat": "Assistant",
    "assistant.browser": "Browser",
    "assistant.addMarkdown": "Add Markdown files",
    "assistant.title": "AI learning assistant",
    "assistant.clear": "Clear",
    "assistant.empty": "Ask a question about “{name}”",
    "assistant.thisConcept": "this concept",
    "assistant.currentConcept": "Current concept",
    "assistant.scrollBottom": "Scroll to bottom",
    "assistant.removeFile": "Remove {name}",
    "assistant.placeholder": "Ask a follow-up...",
    "assistant.addedFiles": "Markdown files attached",
    "assistant.emptyResponse": "No response was generated. Please try again.",
    "assistant.failed": "The assistant could not respond. Please try again.",
    "assistant.fileType": "Only .md files are supported for now. PDF support is coming later.",
    "assistant.fileSize": "Markdown files must be smaller than {size}.",
    "assistant.fileRead": "Could not read the Markdown file. Please select it again.",
    "assistant.prompt.files": "The user attached these Markdown files as context:",
    "assistant.prompt.request": "User request:",
    "assistant.prompt.fallback": "Read these Markdown files first and use them to answer my next questions.",
    "assistant.browser.back": "Browser back",
    "assistant.browser.forward": "Browser forward",
    "assistant.browser.refresh": "Refresh browser",
    "assistant.browser.address": "Browser address",
    "assistant.browser.placeholder": "Enter a URL or localhost:5173",
    "assistant.browser.open": "Open",
    "assistant.browser.embedWarning": "Some websites block embedded views. If you see a connection error, open the page in a new window.",
    "assistant.browser.newWindow": "New window",
    "assistant.browser.title": "Side browser",
    "assistant.browser.empty": "Enter a URL to open a reference beside your lesson",
    "completion.back": "Back to learning session",
    "completion.title": "Learning note",
    "completion.loading": "Loading note...",
    "completion.failed": "Could not load this note",
    "completion.missing": "This note does not exist",
    "completion.export": "Export PDF",
    "completion.generated": "Generated {date}",
    "graph.notFound": "Learning plan not found",
    "graph.home": "Back to home",
    "graph.loading": "Loading...",
    "graph.mastered": "{completed}/{total} mastered",
    "graph.due": "Due {date}",
    "graph.reminderOn": "Reminder on",
    "graph.savedAt": "Saved at {time}",
    "graph.savePlan": "Save plan",
    "graph.settings": "Plan settings",
    "graph.resume": "Resume plan",
    "graph.pause": "Pause plan",
    "graph.share": "Share",
    "graph.editGoal": "Edit goal",
    "graph.complete": "Learning complete!",
    "graph.next": "Recommended next step",
    "graph.relayout": "Arrange by learning path",
    "graph.node": "Concept",
    "graph.learned": "Learned",
    "graph.markLearned": "Mark as learned",
    "graph.deepLearn": "Deep Learn",
    "graph.nodeDeadline": "Concept deadline",
    "graph.deadlineSaving": "Saving",
    "graph.deadlineHint": "Choose today or a future date from the calendar",
    "frequency.customLabel": "Custom frequency",
    "learning.title": "My Learning",
    "learning.tab.profile": "Profile",
    "learning.tab.plans": "Plans",
    "learning.tab.notes": "Notes",
    "learning.tab.stats": "Insights",
    "learning.filter.all": "All",
    "learning.profile.info": "Background",
    "learning.profile.occupation": "Role / identity",
    "learning.profile.occupationPlaceholder": "e.g. third-year computer science student",
    "learning.profile.education": "Education",
    "learning.profile.educationPlaceholder": "e.g. BSc in Information Engineering",
    "learning.profile.programming": "Programming foundation",
    "learning.profile.math": "Math foundation",
    "learning.level.none": "No foundation",
    "learning.level.beginner": "Beginner",
    "learning.level.proficient": "Proficient",
    "learning.profile.abilities": "Strengths",
    "learning.profile.add": "Add",
    "learning.profile.addPrompt": "Add a strength:",
    "learning.profile.mastered": "Mastered knowledge",
    "learning.plans.help": "Review active, paused, completed, and archived plans.",
    "learning.plans.recent": "Last studied {value}",
    "learning.plans.reminder": "Reminder {value}",
    "learning.plans.archiveReason": "Archived: {value}",
    "learning.plans.manual": "Manual",
    "learning.plans.completion": "Completion",
    "learning.plans.open": "Open map",
    "learning.plans.resumeLearning": "Resume learning",
    "learning.plans.pause": "Pause plan",
    "learning.plans.empty": "No learning plans match this filter.",
    "learning.notes.allPlans": "All plans",
    "learning.notes.search": "Search notes...",
    "learning.notes.delete": "Delete note",
    "learning.notes.noMatch": "No matching notes found",
    "learning.notes.empty": "No notes yet",
    "learning.stats.overview": "Overview",
    "learning.stats.completed": "Completed plans",
    "learning.stats.active": "Active",
    "learning.stats.paused": "Paused",
    "learning.stats.archived": "Archived",
    "learning.stats.distribution": "Knowledge areas",
    "learning.stats.uncategorized": "Uncategorized",
    "learning.stats.empty": "Your knowledge-area distribution will appear after you start learning.",
    "graph.clear": "Clear",
    "graph.dateFuture": "Choose today or a future date.",
    "graph.dateSaveHelp": "Choose a date, then select Save to apply it.",
    "graph.why": "Why it matters",
    "graph.usedFor": "Used by: {name}",
    "graph.coreContent": "Core content",
    "graph.explainHint": "Select a topic for an AI explanation",
    "graph.aiExplanation": "AI explanation",
    "graph.saveTopic": "Save “{name}” to notes",
    "graph.saved": "Saved",
    "graph.saveToNotes": "Save to notes",
    "graph.generatingExplanation": "Creating explanation...",
    "graph.prompt": "Learning prompt",
    "graph.resourcesPersist": "These added resources remain after refresh",
    "graph.notes": "Notes",
    "graph.add": "Add",
    "graph.deleteNote": "Delete note",
    "graph.editNoteHint": "Select to edit",
    "graph.notesEmpty": "No notes yet. Capture what you are thinking.",
    "graph.assistant": "AI learning assistant",
    "graph.resizeAssistant": "Drag to resize the assistant",
    "graph.summarize": "Summarize and save",
    "graph.clearChat": "Clear",
    "graph.askAbout": "What would you like to ask about “{name}”?",
    "graph.webSearch": "Search the web",
    "graph.askPlaceholder": "Ask a question...",
    "graph.goal.editTitle": "Edit learning goal",
    "graph.goal.analyze": "Analyze change",
    "graph.goal.analyzing": "Analyzing...",
    "graph.goal.createNew": "Create new plan",
    "graph.goal.apply": "Apply change",
    "graph.goal.current": "Current goal",
    "graph.goal.new": "New goal",
    "graph.goal.placeholder": "Enter the updated learning goal...",
    "graph.goal.large": "This is a major change; a new plan is recommended.",
    "graph.goal.small": "This is a focused adjustment; the current map will be updated.",
    "graph.settings.start": "Start date",
    "graph.settings.target": "Target completion date",
    "graph.settings.frequency": "Study frequency",
    "graph.settings.days": "Days per week",
    "graph.settings.reminders": "Study reminders",
    "graph.settings.remindersHelp": "Use in-app pacing now; system notifications can be connected later.",
    "graph.settings.time": "Reminder time",
    "graph.settings.timezone": "Time zone",
    "graph.settings.save": "Save settings",
    "graph.note.edit": "Edit note",
    "graph.note.new": "New note",
    "graph.note.saveChanges": "Save changes",
    "graph.note.save": "Save note",
    "graph.note.placeholder": "Markdown supported...",
    "graph.leave.title": "Save learning plan?",
    "graph.leave.noSave": "Leave without saving",
    "graph.leave.help": "Save now to continue this plan from the home page later.",
    "graph.resource.searching": "Searching...",
    "graph.resource.added": "Added {count} resources",
    "graph.resource.expanded": "{count} resources added",
    "graph.resource.more": "Find more resources",
    "graph.toast.loadCache": "Could not refresh the map. Showing the local copy.",
    "graph.toast.loadFailed": "Could not load the map. Please try again.",
    "graph.toast.noteUpdated": "Note updated",
    "graph.toast.noteSaved": "Note saved",
    "graph.toast.noResources": "No new high-quality resources were found.",
    "graph.toast.resourceFailed": "Resource search failed. Please try again.",
    "graph.toast.analyzeFailed": "Analysis failed. Please try again.",
    "graph.toast.goalUpdated": "Goal updated",
    "graph.toast.goalFailed": "Could not apply the change. Please try again.",
    "graph.toast.statusFailed": "Could not save the concept status. The previous state was restored.",
    "graph.toast.deadlinePast": "The concept deadline cannot be before today.",
    "graph.toast.deadlineUpdated": "Concept deadline updated",
    "graph.toast.deadlineCleared": "Concept deadline cleared",
    "graph.toast.deadlineFailed": "Could not save the concept deadline.",
    "graph.toast.quizPassed": "Quiz passed. Mastery criteria checked.",
    "graph.toast.planSaved": "Plan saved",
    "graph.toast.saveFailed": "Could not save. Please try again.",
    "graph.toast.settingsUpdated": "Plan settings updated",
    "graph.toast.settingsFailed": "Could not update plan settings.",
    "graph.toast.resumed": "Plan resumed",
    "graph.toast.paused": "Plan paused",
    "graph.shareText": "View my learning plan: {name}",
    "graph.toast.shareOpened": "Share panel opened",
    "graph.toast.linkCopied": "Plan link copied",
    "graph.toast.shareUnsupported": "Sharing is unavailable here. Copy the address-bar link manually.",
    "graph.toast.shareFailed": "Could not share. Please try again.",
    "graph.emptyContent": "No content was generated. Please try again.",
    "graph.explainFailed": "Could not create an explanation. Please try again.",
    "graph.replyFailed": "Could not generate a reply. Please try again.",
    "graph.toast.positionFailed": "Concept positions could not sync; the current canvas remains authoritative.",
    "graph.toast.layoutRetry": "Layout updated. Position sync will retry shortly.",
    "node.resources": "Recommended resources",
    "node.webSearch": "Web search",
    "node.mastery": "Mastery criteria",
    "quiz.title": "Mastery check",
    "quiz.retry": "Try again",
    "quiz.submit": "Submit quiz",
    "quiz.standard": "Criterion",
    "quiz.help": "Three questions. Answer at least two correctly to pass.",
    "quiz.passed": "Passed",
    "quiz.notYet": "Almost there",
    "quiz.score": "You answered {score} of {total} correctly.",
    "loader.analysis.title": "AI is understanding your learning goal",
    "loader.analysis.help": "We are turning your request into a clear objective before building the map.",
    "loader.analysis.boundary": "Mapping the concept boundaries and learning intent",
    "loader.analysis.background": "Identifying your background and priorities",
    "loader.analysis.questions": "Preparing focused clarification questions",
    "loader.analysis.disclosure": "Stages are estimates while the AI reasons. Nothing is saved until you review and confirm the interpreted goal.",
    "loader.graph.title": "Creating your learning map",
    "loader.graph.help": "The map is being structured, generated, and checked before it is saved.",
    "loader.graph.parse": "Analyzing the learning goal",
    "loader.graph.recall": "Finding the core concepts",
    "loader.graph.build": "Building prerequisite relationships",
    "loader.graph.verify": "Checking the map structure",
    "loader.graph.overtime": "Reasoning more deeply about this complex topic...",
    "loader.graph.elapsed": "{count}s elapsed · usually takes 15–30s",
    "loader.graph.nodes": "{ready} of {total} concepts ready",
    "loader.graph.live": "Live output",
    "loader.graph.waiting": "Waiting for the first concepts",
    "loader.graph.conceptsReceived": "concepts received from the AI",
    "loader.graph.disclosure": "Concept counts are live once available. Keep this tab open until the map is ready.",
    "loader.status.running": "In progress",
    "loader.progress.elapsed": "{count}s elapsed",
    "loader.progress.estimated": "Estimated stage",
    "deep.diagramFailed": "[Could not render diagram]",
    "error.eyebrow": "Something went wrong",
    "error.title": "Your last action was not saved",
    "error.help": "The page contained the error so the rest of the app remains safe. Reload and try again, or return home.",
    "error.reload": "Reload and retry",
    "error.home": "Return home",
    "chart.concepts": "{count} concepts",
  },
  "zh-CN": {
    "language.switch": "切换语言",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.saving": "保存中...",
    "common.close": "关闭",
    "common.back": "返回",
    "common.continue": "继续",
    "common.loading": "加载中...",
    "nav.myLearning": "我的学习",
    "nav.signIn": "登录 / 注册",
    "nav.signOut": "退出登录",
    "nav.home": "主页",
    "nav.newMap": "新建学习图谱",
    "nav.workspace": "工作区导航",
    "nav.recentPlans": "最近计划",
    "nav.openMenu": "打开导航",
    "nav.closeMenu": "关闭导航",
    "home.eyebrow": "自适应学习工作台",
    "home.title.before": "今天想",
    "home.title.emphasis": "掌握",
    "home.title.after": "什么？",
    "home.subtitle": "把学习目标转化为聚焦且个性化的概念图谱。",
    "home.goal.placeholder": "例如：我想理解反向传播在神经网络训练中的作用，我有 Python 基础但数学一般...",
    "home.goal.analyzing": "分析中...",
    "home.goal.generate": "生成图谱",
    "home.suggestions.label": "试试示例",
    "home.suggestion.backprop": "理解反向传播算法",
    "home.suggestion.python": "Python 数据分析入门",
    "home.suggestion.transformer": "探索 Transformer 架构",
    "home.today": "今日重点",
    "home.plans": "学习计划",
    "home.progress": "进度",
    "home.lastStudied": "上次学习：{value}",
    "home.justNow": "刚刚",
    "home.continue": "继续学习",
    "home.goLearn": "去学习",
    "home.currentProgress": "当前进度",
    "home.neverStarted": "还没有开始过这条计划",
    "home.daysSince": "距离上次学习 {count} 天",
    "home.setDeadline": "设置截止日期",
    "home.deadline": "截止 {date}",
    "home.reminderOn": "提醒已开启",
    "home.recommendation.ai": "AI 推荐节点",
    "home.recommendation.local": "本地规则推荐节点",
    "home.recommendation.heading": "继续推进下一个关键概念",
    "home.recommendation.fallback": "这是当前最适合推进的下一步。",
    "home.recommendation.localHelp": "AI 暂不可用，已使用依赖关系和截止日期生成推荐。",
    "home.recommendation.loading": "正在生成今日推荐节点...",
    "home.plan.rename": "重命名",
    "home.plan.pause": "暂停",
    "home.plan.resume": "恢复",
    "home.plan.archive": "归档",
    "home.plan.today": "今日推荐",
    "home.plan.next": "下一节点",
    "home.goal.confirmTitle": "确认学习目标",
    "home.goal.edit": "修改输入",
    "home.goal.confirm": "确认生成",
    "home.goal.interpreted": "识别目标",
    "home.goal.purpose": "学习目的",
    "home.purpose.explore": "了解领域",
    "home.purpose.exploreHelp": "更轻的认知入门图谱",
    "home.purpose.apply": "项目实用",
    "home.purpose.applyHelp": "围绕可上手和可实践展开",
    "home.purpose.master": "系统掌握",
    "home.purpose.masterHelp": "更完整、更深入的学习路径",
    "home.deadline.title": "设置截止日期",
    "home.deadline.help": "为「{name}」设置目标完成日期，今日优先级会据此调整。",
    "home.deadline.clear": "清除截止日期",
    "home.deadline.save": "保存日期",
    "home.rename.title": "重命名计划",
    "home.rename.placeholder": "输入新的计划名称",
    "status.active": "进行中",
    "status.paused": "已暂停",
    "status.completed": "已完成",
    "status.archived": "已归档",
    "frequency.daily": "每天学习",
    "frequency.weekly": "每周复盘",
    "frequency.custom": "每周 {count} 次",
    "frequency.flexible": "灵活安排",
    "reminder.overdue": "已拖延",
    "reminder.due": "今日应学",
    "reminder.deadline": "临近截止",
    "reminder.paused": "已暂停提醒",
    "reminder.normal": "节奏正常",
    "reminder.headline.paused": "「{name}」当前已暂停",
    "reminder.headline.onTrack": "今天继续推进「{name}」",
    "reminder.headline.due": "今天适合继续学习「{name}」",
    "reminder.headline.overdue": "「{name}」已经拖延 {count} 天",
    "reminder.headline.deadline": "「{name}」距离目标日期只剩 {count} 天",
    "reminder.detail.paused": "暂停中的计划不会继续催学，你随时可以恢复。",
    "reminder.detail.onTrack": "按当前节奏建议每 {count} 天学习一次。",
    "reminder.detail.due": "按照当前节奏，今天正好适合接着推进这条计划。",
    "reminder.detail.overdue": "你上次学习距今 {count} 天，已经超过当前节奏。",
    "reminder.detail.deadline": "如果你还想按时完成，这几天最好优先推进这条计划。",
    "reminder.detail.deadlinePast": "目标日期已经过去，建议尽快恢复节奏或重新调整计划。",
    "toast.deadlineUpdated": "截止日期已更新",
    "toast.deadlineCleared": "截止日期已清除",
    "toast.deadlineFailed": "截止日期保存失败，已恢复原设置。",
    "toast.signInForAi": "请先登录后再使用 AI 生成功能。",
    "toast.sessionExpired": "登录已过期，请重新登录。",
    "toast.parseFailed": "解析目标失败，请稍后重试。",
    "toast.graphFailed": "生成图谱失败，请稍后重试。",
    "auth.subtitle": "你的自适应学习工作台",
    "auth.login": "登录",
    "auth.register": "注册",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.name": "姓名",
    "auth.passwordHint": "至少 6 位",
    "auth.loggingIn": "登录中...",
    "auth.registering": "注册中...",
    "auth.haveAccount": "已经有账户？",
    "auth.noAccount": "第一次使用 LearningMaster？",
    "auth.agreement": "继续即表示同意服务条款和隐私政策。",
    "auth.error.required": "请填写邮箱和密码。",
    "auth.error.password": "密码长度至少 6 位。",
    "auth.error.email": "邮箱格式不正确。",
    "auth.error.generic": "操作失败，请重试。",
    "auth.error.network": "无法连接服务器，请检查后端服务是否启动。",
    "deep.title": "深入学习",
    "deep.backToMap": "返回图谱",
    "deep.concepts": "概念列表",
    "deep.workspace": "学习区",
    "deep.preparing": "正在准备学习环境...",
    "deep.failed": "学习环境准备失败",
    "deep.resizeConcepts": "调整概念列表和学习区宽度",
    "deep.resizeAssistant": "调整学习区和侧边工作区宽度",
    "deep.resizeHint": "拖动调整宽度，双击重置布局",
    "deep.restart": "重新开始",
    "deep.restartTitle": "确认重新开始？",
    "deep.restartHelp": "当前深入学习进度会被清空，并从第一个概念重新生成讲解。",
    "deep.restartConfirm": "确认重新开始",
    "deep.note.generating": "正在生成笔记...",
    "deep.note.complete": "完成笔记 ↗",
    "deep.note.untitled": "未命名笔记",
    "deep.note.label": "笔记",
    "deep.note.reader": "笔记阅读区",
    "deep.note.edit": "编辑笔记",
    "deep.note.delete": "删除笔记",
    "deep.note.deleteAction": "删除",
    "deep.note.deleteNamed": "删除笔记 {name}",
    "deep.note.close": "关闭笔记阅读",
    "deep.initializing.title": "正在准备第一次深度学习",
    "deep.initializing.subtitle": "{name} 的会话只会初始化一次，之后会自动恢复进度。",
    "deep.initializing.concepts": "读取节点概念列表和学习目标",
    "deep.initializing.depth": "校准当前概念的教学深度",
    "deep.initializing.lesson": "生成第一段讲解和诊断问题",
    "deep.currentConcept": "当前知识点",
    "deep.sidebar": "侧边工作区",
    "deep.conceptsArea": "概念列表区域",
    "deep.sidebarContainer": "侧边工作区容器",
    "deep.progress": "进度",
    "deep.weakPoints": "弱点追踪",
    "deep.answerPrompt": "请回答以下问题：",
    "deep.outline.open": "打开学习目录",
    "deep.outline.question": "问题 {count}",
    "deep.outline.feedback": "评估反馈 {count}",
    "deep.outline.diagram": "图表 {count}",
    "deep.outline.image": "图片 {count}",
    "deep.aiReply": "AI 回复",
    "deep.input.thinking": "AI 正在思考...",
    "deep.input.answer": "输入你的回答...",
    "deep.input.choose": "请选择下一步操作...",
    "deep.send": "发送",
    "deep.pin": "钉到概念区",
    "deep.diagram": "流程图",
    "deep.command.continue": "继续 →",
    "deep.command.expand": "展开",
    "deep.command.skip": "跳过",
    "deep.command.reteach": "重讲",
    "deep.command.confirm_test": "开始测试",
    "deep.command.not_ready": "再复习一下",
    "deep.command.restart": "重新开始",
    "deep.notes": "笔记",
    "deep.note.suggest": "加入笔记？",
    "deep.note.ignore": "忽略",
    "deep.note.add": "加入",
    "deep.note.count": "当前节点共 {count} 条笔记",
    "deep.note.new": "新建笔记",
    "deep.note.empty": "这个节点还没有笔记。",
    "deep.note.editorHelp": "左侧编辑，右侧实时预览",
    "deep.note.saved": "已保存",
    "deep.note.placeholder": "支持 Markdown 语法...",
    "deep.note.preview": "预览区",
    "deep.image.generating": "正在生成图片...",
    "deep.image.failed": "图片生成失败",
    "deep.image.unavailable": "图片不可用",
    "deep.image.loadFailed": "图片加载失败",
    "deep.image.pinned": "钉图区",
    "deep.image.unpin": "取消钉图",
    "deep.image.closePreview": "关闭大图",
    "deep.image.fallbackTitle": "架构图",
    "deep.image.fallbackNote": "可靠降级方案",
    "deep.image.fallbackAria": "{name}架构图",
    "deep.image.fallbackTopic": "学习概念",
    "deep.image.concept": "概念",
    "deep.image.mechanism": "机制",
    "deep.image.outcome": "结果",
    "deep.search.searching": "正在联网搜索资料...",
    "deep.search.fallback": "未获取到外部资料，已切换为普通回答。",
    "deep.search.done": "参考资料已整理完成。",
    "deep.sources": "参考来源",
    "assistant.chat": "侧边聊天",
    "assistant.browser": "浏览器",
    "assistant.addMarkdown": "添加 Markdown 文件",
    "assistant.title": "AI 学习助手",
    "assistant.clear": "清空",
    "assistant.empty": "问一个关于“{name}”的问题",
    "assistant.thisConcept": "这个概念",
    "assistant.currentConcept": "当前知识点",
    "assistant.scrollBottom": "滚动到底部",
    "assistant.removeFile": "移除 {name}",
    "assistant.placeholder": "要求后续变更",
    "assistant.addedFiles": "已添加 Markdown 文件",
    "assistant.emptyResponse": "暂时没有生成内容，请再试一次。",
    "assistant.failed": "助手回复失败，请稍后重试。",
    "assistant.fileType": "目前只支持添加 .md 文件，PDF 会在后续版本支持。",
    "assistant.fileSize": "Markdown 文件不能超过 {size}。",
    "assistant.fileRead": "读取 Markdown 文件失败，请重新选择。",
    "assistant.prompt.files": "用户附加了以下 Markdown 文件作为上下文：",
    "assistant.prompt.request": "用户请求：",
    "assistant.prompt.fallback": "请先阅读这些 Markdown 文件，并基于文件内容回答我后续的问题。",
    "assistant.browser.back": "浏览器后退",
    "assistant.browser.forward": "浏览器前进",
    "assistant.browser.refresh": "刷新浏览器",
    "assistant.browser.address": "浏览器地址",
    "assistant.browser.placeholder": "输入网址或 localhost:5173",
    "assistant.browser.open": "打开",
    "assistant.browser.embedWarning": "部分网站会拒绝在侧边栏内嵌显示，遇到“拒绝连接”时请新窗口打开。",
    "assistant.browser.newWindow": "新窗口",
    "assistant.browser.title": "侧边浏览器",
    "assistant.browser.empty": "输入网址，在右侧打开参考页面",
    "completion.back": "返回学习页",
    "completion.title": "学习笔记",
    "completion.loading": "加载笔记中...",
    "completion.failed": "无法加载笔记内容",
    "completion.missing": "笔记不存在",
    "completion.export": "导出 PDF",
    "completion.generated": "生成于 {date}",
    "graph.notFound": "未找到学习计划",
    "graph.home": "返回首页",
    "graph.loading": "加载中...",
    "graph.mastered": "{completed}/{total} 已掌握",
    "graph.due": "截止 {date}",
    "graph.reminderOn": "已开启提醒",
    "graph.savedAt": "已保存于 {time}",
    "graph.savePlan": "保存计划",
    "graph.settings": "计划设置",
    "graph.resume": "恢复计划",
    "graph.pause": "暂停计划",
    "graph.share": "分享",
    "graph.editGoal": "修改目标",
    "graph.complete": "学习完成！",
    "graph.next": "推荐下一步",
    "graph.relayout": "按学习路径整理布局",
    "graph.node": "知识节点",
    "graph.learned": "已学习",
    "graph.markLearned": "标记已学",
    "graph.deepLearn": "深入学习",
    "graph.nodeDeadline": "节点截止日期",
    "graph.deadlineSaving": "保存中",
    "graph.deadlineHint": "请通过日历选择今天或之后的日期",
    "frequency.customLabel": "自定义频率",
    "learning.title": "我的学习",
    "learning.tab.profile": "我的画像",
    "learning.tab.plans": "学习计划",
    "learning.tab.notes": "全部笔记",
    "learning.tab.stats": "学习统计",
    "learning.filter.all": "全部",
    "learning.profile.info": "基础信息",
    "learning.profile.occupation": "职业 / 身份",
    "learning.profile.occupationPlaceholder": "例如：大三计算机学生",
    "learning.profile.education": "教育背景",
    "learning.profile.educationPlaceholder": "例如：信息工程本科",
    "learning.profile.programming": "编程基础",
    "learning.profile.math": "数学基础",
    "learning.level.none": "无基础",
    "learning.level.beginner": "入门",
    "learning.level.proficient": "熟练",
    "learning.profile.abilities": "能力标签",
    "learning.profile.add": "添加",
    "learning.profile.addPrompt": "添加新的能力标签：",
    "learning.profile.mastered": "已掌握知识",
    "learning.plans.help": "区分进行中、暂停中、已完成和已归档的计划状态。",
    "learning.plans.recent": "最近学习 {value}",
    "learning.plans.reminder": "提醒 {value}",
    "learning.plans.archiveReason": "归档原因：{value}",
    "learning.plans.manual": "手动",
    "learning.plans.completion": "完成度",
    "learning.plans.open": "打开图谱",
    "learning.plans.resumeLearning": "恢复学习",
    "learning.plans.pause": "暂停计划",
    "learning.plans.empty": "当前筛选下还没有学习计划。",
    "learning.notes.allPlans": "全部计划",
    "learning.notes.search": "搜索笔记...",
    "learning.notes.delete": "删除笔记",
    "learning.notes.noMatch": "没有找到匹配的笔记",
    "learning.notes.empty": "暂时还没有笔记",
    "learning.stats.overview": "总览",
    "learning.stats.completed": "已完成计划",
    "learning.stats.active": "进行中",
    "learning.stats.paused": "已暂停",
    "learning.stats.archived": "已归档",
    "learning.stats.distribution": "知识领域分布",
    "learning.stats.uncategorized": "未分类",
    "learning.stats.empty": "开始学习后，这里会显示你的知识领域分布。",
    "graph.clear": "清除",
    "graph.dateFuture": "只能选择今天或之后的日期。",
    "graph.dateSaveHelp": "选择日期后点击保存才会生效。",
    "graph.why": "为什么学",
    "graph.usedFor": "用于：{name}",
    "graph.coreContent": "核心内容",
    "graph.explainHint": "点击主题获取 AI 解释",
    "graph.aiExplanation": "AI 解释",
    "graph.saveTopic": "保存主题“{name}”到笔记",
    "graph.saved": "已保存",
    "graph.saveToNotes": "保存到笔记",
    "graph.generatingExplanation": "AI 正在生成解释...",
    "graph.prompt": "学习 Prompt",
    "graph.resourcesPersist": "刷新页面后也会保留这些扩展资源",
    "graph.notes": "笔记",
    "graph.add": "添加",
    "graph.deleteNote": "删除笔记",
    "graph.editNoteHint": "点击即可编辑",
    "graph.notesEmpty": "这里还没有内容，记下你的思考吧。",
    "graph.assistant": "AI 学习助手",
    "graph.resizeAssistant": "拖动调整助手窗口大小",
    "graph.summarize": "总结并保存",
    "graph.clearChat": "清空",
    "graph.askAbout": "有什么关于“{name}”的问题？",
    "graph.webSearch": "联网搜索",
    "graph.askPlaceholder": "问一个问题...",
    "graph.goal.editTitle": "修改学习目标",
    "graph.goal.analyze": "分析变更",
    "graph.goal.analyzing": "分析中...",
    "graph.goal.createNew": "新建计划",
    "graph.goal.apply": "应用修改",
    "graph.goal.current": "当前目标",
    "graph.goal.new": "新目标",
    "graph.goal.placeholder": "输入修改后的学习目标...",
    "graph.goal.large": "目标变化较大，建议新建计划。",
    "graph.goal.small": "小幅调整，将更新现有图谱。",
    "graph.settings.start": "开始日期",
    "graph.settings.target": "目标完成日期",
    "graph.settings.frequency": "学习频率",
    "graph.settings.days": "每周次数",
    "graph.settings.reminders": "学习提醒",
    "graph.settings.remindersHelp": "先用站内节奏管理，后续再接系统提醒。",
    "graph.settings.time": "提醒时间",
    "graph.settings.timezone": "时区",
    "graph.settings.save": "保存设置",
    "graph.note.edit": "编辑笔记",
    "graph.note.new": "新笔记",
    "graph.note.saveChanges": "保存修改",
    "graph.note.save": "保存笔记",
    "graph.note.placeholder": "支持 Markdown 格式...",
    "graph.leave.title": "保存学习计划？",
    "graph.leave.noSave": "不保存",
    "graph.leave.help": "保存后可在首页继续学习。",
    "graph.resource.searching": "搜索中...",
    "graph.resource.added": "已补充 {count} 条资源",
    "graph.resource.expanded": "已扩展 {count} 条资源",
    "graph.resource.more": "搜索更多资源",
    "graph.toast.loadCache": "图谱加载失败，已显示本地缓存。",
    "graph.toast.loadFailed": "图谱加载失败，请稍后重试。",
    "graph.toast.noteUpdated": "笔记已更新",
    "graph.toast.noteSaved": "笔记已保存",
    "graph.toast.noResources": "暂未找到新的高质量资源。",
    "graph.toast.resourceFailed": "资源搜索失败，请重试。",
    "graph.toast.analyzeFailed": "分析失败，请重试。",
    "graph.toast.goalUpdated": "目标已更新",
    "graph.toast.goalFailed": "应用修改失败，请重试。",
    "graph.toast.statusFailed": "节点状态保存失败，已恢复原状态。",
    "graph.toast.deadlinePast": "节点截止日期不能早于今天。",
    "graph.toast.deadlineUpdated": "节点截止日期已更新",
    "graph.toast.deadlineCleared": "节点截止日期已清除",
    "graph.toast.deadlineFailed": "节点截止日期保存失败，请重试。",
    "graph.toast.quizPassed": "小测通过，掌握标准已打勾。",
    "graph.toast.planSaved": "计划已保存",
    "graph.toast.saveFailed": "保存失败，请重试。",
    "graph.toast.settingsUpdated": "学习计划设置已更新",
    "graph.toast.settingsFailed": "更新计划设置失败。",
    "graph.toast.resumed": "计划已恢复",
    "graph.toast.paused": "计划已暂停",
    "graph.shareText": "查看我的学习计划：{name}",
    "graph.toast.shareOpened": "分享面板已打开",
    "graph.toast.linkCopied": "计划链接已复制",
    "graph.toast.shareUnsupported": "当前环境暂不支持分享，请手动复制地址栏链接。",
    "graph.toast.shareFailed": "分享失败，请重试。",
    "graph.emptyContent": "内容生成为空，请重试。",
    "graph.explainFailed": "解释生成失败，请重试。",
    "graph.replyFailed": "回复失败，请重试。",
    "graph.toast.positionFailed": "节点位置同步失败，稍后会以当前画布为准。",
    "graph.toast.layoutRetry": "路径布局已更新，位置同步稍后会重试。",
    "node.resources": "推荐资源",
    "node.webSearch": "联网搜索",
    "node.mastery": "掌握标准",
    "quiz.title": "掌握标准小测",
    "quiz.retry": "重新作答",
    "quiz.submit": "提交小测",
    "quiz.standard": "测试标准",
    "quiz.help": "共 3 题，答对 2 题及以上即通过。",
    "quiz.passed": "已通过",
    "quiz.notYet": "还差一点",
    "quiz.score": "本次答对 {score} / {total} 题。",
    "loader.analysis.title": "AI 正在理解你的学习目标",
    "loader.analysis.help": "在生成图谱前，先把你的请求整理成清晰、可执行的学习目标。",
    "loader.analysis.boundary": "解析概念边界与学习意图",
    "loader.analysis.background": "识别你的背景与目标重点",
    "loader.analysis.questions": "准备更清晰的学习澄清问题",
    "loader.analysis.disclosure": "AI 推理期间的阶段为估算信息。你查看并确认目标前，不会保存任何学习图谱。",
    "loader.graph.title": "正在为你生成学习图谱",
    "loader.graph.help": "图谱正在进行结构规划、内容生成和结果校验，完成后才会保存。",
    "loader.graph.parse": "解析学习目标",
    "loader.graph.recall": "召回学科核心概念",
    "loader.graph.build": "构建知识依赖关系",
    "loader.graph.verify": "校验图谱结构",
    "loader.graph.overtime": "正在为更复杂的主题做更深推理...",
    "loader.graph.elapsed": "已用 {count} 秒，通常需要 15–30 秒",
    "loader.graph.nodes": "{ready} / {total} 个节点已完成",
    "loader.graph.live": "实时输出",
    "loader.graph.waiting": "正在等待首批概念",
    "loader.graph.conceptsReceived": "个概念已由 AI 返回",
    "loader.graph.disclosure": "节点计数在后端返回后实时更新。图谱完成前请保持当前页面打开。",
    "loader.status.running": "正在处理",
    "loader.progress.elapsed": "已用 {count} 秒",
    "loader.progress.estimated": "估算阶段",
    "deep.diagramFailed": "[图表渲染失败]",
    "error.eyebrow": "页面遇到错误",
    "error.title": "当前操作没有保存成功",
    "error.help": "页面已拦截异常，避免影响整个应用。你可以刷新后重试，或先回到首页。",
    "error.reload": "刷新重试",
    "error.home": "回到首页",
    "chart.concepts": "{count} 个知识点",
  },
};

const interpolate = (value, variables = {}) =>
  Object.entries(variables).reduce(
    (result, [key, replacement]) =>
      result.replaceAll(`{${key}}`, String(replacement ?? "")),
    value,
  );

const translate = (language, key, variables) => {
  const value = messages[language]?.[key] ?? messages[DEFAULT_LANGUAGE]?.[key] ?? key;
  return interpolate(value, variables);
};

const fallbackValue = {
  // Legacy isolated renders (unit tests, stories) keep their historical locale.
  // The actual application always uses LanguageProvider and defaults to English.
  language: "zh-CN",
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key, variables) => translate("zh-CN", key, variables),
};

export const LanguageContext = createContext(fallbackValue);

const getInitialLanguage = () => {
  if (typeof window === "undefined") return DEFAULT_LANGUAGE;
  const savedLanguage = window.localStorage.getItem(STORAGE_KEY);
  return savedLanguage === "zh-CN" || savedLanguage === "en"
    ? savedLanguage
    : DEFAULT_LANGUAGE;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "zh-CN" : "en")),
      t: (key, variables) => translate(language, key, variables),
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);

export { DEFAULT_LANGUAGE, STORAGE_KEY };
